name: productivity_hub
description: A study productivity app with to-do list, planner, pomodoro timer, notes, GPA calculator, and quotes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  usage_stats: ^1.3.1
  crypto: ^3.0.3
  translator: ^1.0.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon_background.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#1C2B24"
    theme_color: "#1C2B24"

flutter_native_splash:
  color: "#1C2B24"
  image: assets/icon/splash_logo.png
  color_dark: "#1C2B24"
  image_dark: assets/icon/splash_logo.png
  android_12:
    image: assets/icon/splash_logo.png
    icon_background_color: "#1C2B24"
    image_dark: assets/icon/splash_logo.png
    icon_background_color_dark: "#1C2B24"
  web: false
